name: CI/CD Pipeline for Townmanor.ai

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set Up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    # Step 3: Install Dependencies and Build Project
    - name: Install dependencies
      run: npm ci

    - name: Build React app
      run: npm run build

    # Step 4: Check if Build Directory Exists and Create Archive
    - name: Check if Build Directory Exists
      run: |
        if [ -d "build" ]; then
          echo "Build directory exists, proceeding with creating archive."
        else
          echo "Build directory does not exist, aborting."
          exit 1
        fi

    - name: Create Build Archive
      run: tar -czvf react-build.tar.gz -C build .

    # Step 5: Deploy to AWS EC2
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ec2-43-205-18-191.ap-south-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Navigate to deployment directory
          cd /home/ubuntu/frontend/_work/Townmanor.ai/Townmanor.ai

          # Backup the current build (if exists)
          if [ -d "dist" ]; then
            echo "Backing up current dist folder..."
            mv dist dist_backup_$(date +%s)
          fi

          # Create the dist directory and extract the new build
          echo "Extracting new build..."
          mkdir -p dist
          rm -rf dist/*
          tar -xzvf react-build.tar.gz -C dist

          # Check if the build was successfully extracted
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "Error: Build extraction failed. Restoring previous build..."
            mv dist_backup_* dist
            exit 1
          fi

          # Check if Nginx is serving the new build correctly
          echo "Verifying deployment..."
          if curl -Is http://your-server-ip | grep -q "200 OK"; then
            echo "New build verified successfully."
          else
            echo "Deployment failed! Restoring previous build."
            mv dist_backup_* dist
            exit 1
          fi

          # Restart Nginx
          echo "Restarting Nginx..."
          sudo systemctl restart nginx

    # Step 6: Archive React build (Optional)
    - name: Archive React build
      uses: actions/upload-artifact@v3
      with:
        name: react-build
        path: react-build.tar.gz
